ShoppingSystemMVC/Controllers/CategoryViewController.cs
using Newtonsoft.Json;
using ShoppingSystemMVC.Models;
using ShoppingSystemMVC.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ShoppingSystemMVC.Controllers
{
    public class CategoryViewController : Controller
    {
        //// GET: CategoryView
         public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> CategoryDetails()
        {
            List<CategoryViewModel> Category = new List<CategoryViewModel>();
            var service = new UserServiceRepository();
            {
                using (var response = service.GetResponse("Category"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    Category = JsonConvert.DeserializeObject<List<CategoryViewModel>>(apiResponse);
                }
            }
            return View(Category);
        }

        public async Task<ActionResult> ItemDetails()
        {
            List<ItemViewModel> Item = new List<ItemViewModel>();
            var service = new UserServiceRepository();
            {
                using (var response = service.GetResponse("Item"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    Item = JsonConvert.DeserializeObject<List<ItemViewModel>>(apiResponse);
                }
            }
            return View(Item);
        }

        public async Task<ActionResult> CartDetails()
        {
            List<CartViewModel> Cart = new List<CartViewModel>();
            var service = new UserServiceRepository();
            {
                using (var response = service.GetResponse("Cart"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    Cart = JsonConvert.DeserializeObject<List<CartViewModel>>(apiResponse);
                }
            }
            return View(Cart);
        }

        //adding through MVC
        #region ADD TO CART
        public async Task<ActionResult> AddCart(CartViewModel cartView)
        {
            if (ModelState.IsValid)
            {
                CartViewModel cart = new CartViewModel();
                var service = new UserServiceRepository();
                {
                    using (var response = service.PostResponse("Cart", cartView))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        //user = JsonConvert.DeserializeObject<UserViewModel>(apiResponse);
                    }
                }
              //  return RedirectToAction("CartDetails");
            }
            return View(cartView);
        }
        #endregion


    }
}

ShoppingSystemMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - P A C T</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <!-- Bootstrap and JQuery CDNs -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <!-- Navbar content -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            @*<a class="navbar-brand" href="#">Hidden brand</a>*@
            @Html.ActionLink("P A C T", "Index", "Home", null,
           new { @class = "navbar-brand font-weight-bold" })
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    @*<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>*@
                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item active">
                    @*<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>*@
                    @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item active">
                    @*<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>*@
                    @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })
                </li>
            </ul>
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                @{
                    if (Request.IsAuthenticated)
                    {
                        <li class="nav-item active">@Html.ActionLink("List Of Users", "RegisterdUsers", "Userview", null, new { @class = "nav-link" })</li>
                        <li class="nav-item active">
                            @Html.ActionLink("Welcome " + User.Identity.Name, "", "", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item active">@Html.ActionLink("LogOff", "LogOff", "Userview", null, new { @class = "nav-link" })</li>
                    }
                    else
                    {
                        <li class="nav-item active">
                            @Html.ActionLink("Register", "Registration", "Userview", null, new { @class = "nav-link" })
                        </li>
                        @*class="disabled"*@
                        <li class="nav-item active">
                            @Html.ActionLink("Login", "Login", "Userview", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item active">
                            @Html.ActionLink("Cart", "CartDetails", "CategoryView", null, new { @class = "nav-link" })
                        </li>
                    }
                }

            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-warning my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="container body-content">
        <div>
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p class="text-right text-info font-weight-bold">&copy; copy right to PACT @DateTime.Now.Year - P A C T</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>